[colors.bright]
black = "0x555555"
blue = "0xcaa9fa"
cyan = "0x8be9fd"
green = "0x50fa7b"
magenta = "0xff79c6"
red = "0xff5555"
white = "0xffffff"
yellow = "0xf1fa8c"

[colors.normal]
black = "0x000000"
blue = "0xbd93f9"
cyan = "0x8be9fd"
green = "0x50fa7b"
magenta = "0xff79c6"
red = "0xff5555"
white = "0xbbbbbb"
yellow = "0xf1fa8c"

[colors.primary]
background = "0x282a36"
foreground = "0xf8f8f2"

[font]
size = 10.0

[font.bold]
family = "LiberationMono"
style = "Bold"

[font.bold_italic]
family = "LiberationMono"
style = "Bold Italic"

[font.italic]
family = "LiberationMono"
style = "Italic"

[font.normal]
family = "LiberationMono"
style = "Bold"

[scrolling]
history = 50000

[shell]
program = "xonsh"

[window]
dynamic_title = true
opacity = 0.85
