#____________________________________________________________________
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
keybinding:
  universal:
    quit          : 'Q'
    prevItem-alt  : 'i' # go one line up
    nextItem-alt  : 'k' # go one line down
    prevBlock-alt : 'j' # goto the previous block / panel
    nextBlock-alt : 'l' # goto the next block / panel
  files:
    ignoreFile    : 'I'
os:
  edit            : 'lvim {{filename}}'
gui:
  nerdFontsVersion: "3"
